name: main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: git clone https://github.com/michioxd/hammer
      - run: python ./hammer/hammer.py -s muzipa.xyz -p 80
